### ISSUE TITLE
import tensorflow throws error on np.object

### ISSUE THREAD

**Issue by Soraki23** [Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide#17]
Hi and first of all thank you for sharing this. I managed to follow all the instructions in a rigorous and clean manner, though I get the the following errors when trying to execute `import tensorflow as tf`:
`/home/user/.local/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:513: FutureWarning: In the future np.object will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util`
I tried the fix you described below, but it did not solve the problem.
Has there been minor updates of any of the used packages that could have broken functionality? I don't know these python libraries, so I did not try to investigate them further.
Regards

**Comment by Grench6** [comment]
Hi. Its just a future deprecation warning because of the installed tensorflow version, it can be safely ignored for the moment.
